[package]
name = "gencsv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.0", features = ["derive"] }
fake = "2.6.1"

[dev-dependencies]
assert_cmd = "2.0.11"
predicates = "3.0.3"
